services:
  db:
    image: postgres:16.6
    container_name: et_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=et_db
    ports:
      - "5432:5432"
    networks:
      - et_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: et_backend
    depends_on:
      - db
    restart: always
    env_file:
      - backend/.env-dev
    ports:
      - "8080:8080"
    networks:
      - et_network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: et_frontend
    ports:
      - "5173:5173"
    networks:
      - et_network

volumes:
  postgres_data:

networks:
  et_network:
    driver: bridge