version: "3.9"

services:
  db:
    image: postgres:16
    container_name: et_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=et_db
    ports:
      - "5432:5432"
    networks:
      - et_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  et_network:
    driver: bridge